// Generated by scripts/build-tokens.mjs from tokens/cheddar.tokens.json.
// Do not edit by hand — edit the JSON and run `npm run tokens:build`.

import SwiftUI

public struct CheddarColor: Equatable, Sendable {
    public let red: Double
    public let green: Double
    public let blue: Double
    public let opacity: Double

    public init(red: Double, green: Double, blue: Double, opacity: Double = 1) {
        self.red = red
        self.green = green
        self.blue = blue
        self.opacity = opacity
    }

    public var color: Color {
        Color(.sRGB, red: red, green: green, blue: blue, opacity: opacity)
    }
}

public struct CheddarTextStyle: Equatable, Sendable {
    public let family: String
    public let size: CGFloat
    public let weight: Font.Weight
    public let lineHeight: CGFloat

    public var font: Font { .custom(family, size: size) }
}

public enum CheddarBrand: String, CaseIterable, Sendable {
    case magenta
    case blue
    case green
    case purple
}

/// The three token resolutions. `brand` is the product app shell — a saturated
/// brand-100 canvas with light surfaces — not dark mode.
public enum CheddarAppearance: String, CaseIterable, Sendable {
    case light
    case dark
    case brand
}

public enum CheddarPrimitives {
    public static let black100 = CheddarColor(red: 0, green: 0, blue: 0, opacity: 1)
    public static let black200 = CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.8)
    public static let black300 = CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56)
    public static let black400 = CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
    public static let black500 = CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2)
    public static let black600 = CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08)
    public static let white100 = CheddarColor(red: 1, green: 1, blue: 1, opacity: 1)
    public static let white200 = CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.8)
    public static let white300 = CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6)
    public static let white400 = CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4)
    public static let white500 = CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2)
    public static let white600 = CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1)
    public static let brand100 = CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1)
    public static let brand200 = CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1)
    public static let brand300 = CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1)
    public static let brand400 = CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1)
    public static let brand500 = CheddarColor(red: 1, green: 0.77647, blue: 0.97255, opacity: 1)
    public static let brand600 = CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1)
    public static let green100 = CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1)
    public static let green200 = CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1)
    public static let green300 = CheddarColor(red: 0.35294, green: 0.72941, blue: 0, opacity: 1)
    public static let green400 = CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1)
    public static let green500 = CheddarColor(red: 0.83137, green: 1, blue: 0.44706, opacity: 1)
    public static let green600 = CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1)
    public static let purple100 = CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1)
    public static let purple200 = CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1)
    public static let purple300 = CheddarColor(red: 0.46667, green: 0.27843, blue: 1, opacity: 1)
    public static let purple400 = CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1)
    public static let purple500 = CheddarColor(red: 0.80784, green: 0.7451, blue: 1, opacity: 1)
    public static let purple600 = CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1)
    public static let blue100 = CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1)
    public static let blue200 = CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1)
    public static let blue300 = CheddarColor(red: 0, green: 0.48235, blue: 0.93333, opacity: 1)
    public static let blue400 = CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1)
    public static let blue500 = CheddarColor(red: 0.6, green: 0.93333, blue: 1, opacity: 1)
    public static let blue600 = CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1)
    public static let red100 = CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1)
    public static let red200 = CheddarColor(red: 0.54902, green: 0.03922, blue: 0.12941, opacity: 1)
    public static let red300 = CheddarColor(red: 0.84706, green: 0.10588, blue: 0.23529, opacity: 1)
    public static let red400 = CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1)
    public static let red500 = CheddarColor(red: 1, green: 0.70196, blue: 0.75294, opacity: 1)
    public static let red600 = CheddarColor(red: 1, green: 0.89412, blue: 0.91373, opacity: 1)
    public static let neutral700 = CheddarColor(red: 0.14902, green: 0.13725, blue: 0.14902, opacity: 1)
    public static let neutral800 = CheddarColor(red: 0.11765, green: 0.1098, blue: 0.11765, opacity: 1)
    public static let neutral900 = CheddarColor(red: 0.06667, green: 0.06275, blue: 0.06667, opacity: 1)
    public static let cheddarBlackCherry = CheddarColor(red: 0.1451, green: 0.12157, blue: 0.13725, opacity: 1)
    public static let cheddarOrange = CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1)
}

public enum CheddarSize {
    public static let border: CGFloat = 1
    public static let iconStroke: CGFloat = 1
    public static let paddingXxxs: CGFloat = 2
    public static let paddingXxs: CGFloat = 4
    public static let paddingXs: CGFloat = 8
    public static let paddingS: CGFloat = 12
    public static let paddingM: CGFloat = 16
    public static let paddingL: CGFloat = 24
    public static let paddingXl: CGFloat = 32
    public static let paddingXxl: CGFloat = 40
    public static let gapXs: CGFloat = 4
    public static let gapS: CGFloat = 8
    public static let gapM: CGFloat = 16
    public static let gapL: CGFloat = 24
    public static let fontXs: CGFloat = 14
    public static let fontS: CGFloat = 16
    public static let fontM: CGFloat = 18
    public static let fontL: CGFloat = 24
    public static let fontXl: CGFloat = 64
    public static let fontDisplay: CGFloat = 80
    public static let cornerXxsmall: CGFloat = 4
    public static let cornerXsmall: CGFloat = 8
    public static let cornerSmall: CGFloat = 12
    public static let cornerMedium: CGFloat = 16
    public static let cornerLarge: CGFloat = 24
    public static let cornerXlarge: CGFloat = 40
    public static let cornerFull: CGFloat = 9999
    public static let iconSmall: CGFloat = 12
    public static let iconMedium: CGFloat = 16
    public static let iconLarge: CGFloat = 24
}

public enum CheddarType {
    public static let displayXlarge = CheddarTextStyle(family: "Oswald", size: 80, weight: .medium, lineHeight: 80)
    public static let displayLarge = CheddarTextStyle(family: "Oswald", size: 64, weight: .semibold, lineHeight: 64)
    public static let displayMedium = CheddarTextStyle(family: "Oswald", size: 48, weight: .medium, lineHeight: 48)
    public static let displaySmall = CheddarTextStyle(family: "Oswald", size: 24, weight: .medium, lineHeight: 24)
    public static let displayXsmall = CheddarTextStyle(family: "Oswald", size: 21, weight: .medium, lineHeight: 21)
    public static let heading = CheddarTextStyle(family: "Mona Sans Variable", size: 24, weight: .medium, lineHeight: 33.6)
    public static let bodyLarge = CheddarTextStyle(family: "Mona Sans Variable", size: 16, weight: .medium, lineHeight: 20.8)
    public static let bodyLargeStrong = CheddarTextStyle(family: "Mona Sans Variable", size: 16, weight: .semibold, lineHeight: 20.8)
    public static let bodyMedium = CheddarTextStyle(family: "Mona Sans Variable", size: 14, weight: .medium, lineHeight: 18.2)
    public static let bodyMediumStrong = CheddarTextStyle(family: "Mona Sans Variable", size: 14, weight: .bold, lineHeight: 18.2)
    public static let bodySmall = CheddarTextStyle(family: "Mona Sans Variable", size: 12, weight: .medium, lineHeight: 15.6)
    public static let bodySmallStrong = CheddarTextStyle(family: "Mona Sans Variable", size: 12, weight: .semibold, lineHeight: 15.6)
}

public enum CheddarTokens {
    public struct Ramp: Equatable, Sendable {
        public let step100: CheddarColor
        public let step200: CheddarColor
        public let step300: CheddarColor
        public let step400: CheddarColor
        public let step500: CheddarColor
        public let step600: CheddarColor
    }

    public struct Semantic: Equatable, Sendable {
        public let foregroundPrimary: CheddarColor
        public let foregroundSecondary: CheddarColor
        public let foregroundTertiary: CheddarColor
        public let foregroundBrandPrimary: CheddarColor
        public let foregroundBrandSecondary: CheddarColor
        public let foregroundBrandTertiary: CheddarColor
        public let foregroundBrandHighlight: CheddarColor
        public let foregroundOnReverse: CheddarColor
        public let foregroundOnReverseSecondary: CheddarColor
        public let foregroundBrandReverse: CheddarColor
        public let foregroundBrandReverseSecondary: CheddarColor
        public let foregroundBrandReverseTertiary: CheddarColor
        public let foregroundDanger: CheddarColor
        public let foregroundSuccess: CheddarColor
        public let foregroundWarning: CheddarColor
        public let foregroundOnSurface: CheddarColor
        public let foregroundOnSurfaceSecondary: CheddarColor
        public let foregroundOnSurfaceTertiary: CheddarColor
        public let bgBrandPrimary: CheddarColor
        public let bgBrandSecondary: CheddarColor
        public let bgBrandTertiary: CheddarColor
        public let bgBrandShade: CheddarColor
        public let bgOnBrand: CheddarColor
        public let bgDanger: CheddarColor
        public let bgScrim: CheddarColor
        public let iconPrimary: CheddarColor
        public let iconSecondary: CheddarColor
        public let backgroundDefault: CheddarColor
        public let backgroundSurface: CheddarColor
        public let backgroundMuted: CheddarColor
        public let backgroundOverlay: CheddarColor
        public let borderDefault: CheddarColor
        public let borderStrong: CheddarColor
        public let borderFocus: CheddarColor
        public let borderDanger: CheddarColor
        public let trackDefault: CheddarColor
        public let shadowSurface: CheddarColor
        public let shadowControl: CheddarColor
    }

    /// The accent ramp for a brand. Every brand-derived semantic color follows it.
    public static func ramp(_ brand: CheddarBrand) -> Ramp {
        switch brand {
        case .magenta:
            return Ramp(
                step100: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
                step200: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
                step300: CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1),
                step400: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
                step500: CheddarColor(red: 1, green: 0.77647, blue: 0.97255, opacity: 1),
                step600: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1)
            )
        case .blue:
            return Ramp(
                step100: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
                step200: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
                step300: CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1),
                step400: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
                step500: CheddarColor(red: 1, green: 0.77647, blue: 0.97255, opacity: 1),
                step600: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1)
            )
        case .green:
            return Ramp(
                step100: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
                step200: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
                step300: CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1),
                step400: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
                step500: CheddarColor(red: 1, green: 0.77647, blue: 0.97255, opacity: 1),
                step600: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1)
            )
        case .purple:
            return Ramp(
                step100: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
                step200: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
                step300: CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1),
                step400: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
                step500: CheddarColor(red: 1, green: 0.77647, blue: 0.97255, opacity: 1),
                step600: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1)
            )
        }
    }

    /// Semantic palette for an appearance and brand, with alpha preserved.
    public static func semantic(
        appearance: CheddarAppearance = .light,
        brand: CheddarBrand = .magenta
    ) -> Semantic {
        switch appearance {
    case .light:
        switch brand {
        case .magenta:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            foregroundBrandPrimary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundBrandReverse: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            foregroundDanger: CheddarColor(red: 0.54902, green: 0.03922, blue: 0.12941, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 1, green: 0.77647, blue: 0.97255, opacity: 1),
            bgBrandShade: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            bgOnBrand: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            bgDanger: CheddarColor(red: 1, green: 0.89412, blue: 0.91373, opacity: 1),
            bgScrim: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            iconSecondary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.96353, green: 0.94, blue: 0.95059, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.94529, green: 0.91, blue: 0.92588, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            borderDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            borderStrong: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            borderFocus: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            borderDanger: CheddarColor(red: 0.84706, green: 0.10588, blue: 0.23529, opacity: 1),
            trackDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            shadowSurface: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 0.08),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2)
            )
        case .blue:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            foregroundBrandPrimary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundBrandReverse: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            foregroundDanger: CheddarColor(red: 0.54902, green: 0.03922, blue: 0.12941, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.6, green: 0.93333, blue: 1, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            bgOnBrand: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            bgDanger: CheddarColor(red: 1, green: 0.89412, blue: 0.91373, opacity: 1),
            bgScrim: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            iconSecondary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.94235, green: 0.94, blue: 0.97365, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.91353, green: 0.91, blue: 0.96047, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            borderDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            borderStrong: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            borderFocus: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            borderDanger: CheddarColor(red: 0.84706, green: 0.10588, blue: 0.23529, opacity: 1),
            trackDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            shadowSurface: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 0.08),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2)
            )
        case .green:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            foregroundBrandPrimary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundBrandReverse: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundDanger: CheddarColor(red: 0.54902, green: 0.03922, blue: 0.12941, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.83137, green: 1, blue: 0.44706, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            bgOnBrand: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            bgDanger: CheddarColor(red: 1, green: 0.89412, blue: 0.91373, opacity: 1),
            bgScrim: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            iconSecondary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.94235, green: 0.95412, blue: 0.94, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.91353, green: 0.93118, blue: 0.91, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            borderDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            borderStrong: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            borderFocus: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            borderDanger: CheddarColor(red: 0.84706, green: 0.10588, blue: 0.23529, opacity: 1),
            trackDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            shadowSurface: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 0.08),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2)
            )
        case .purple:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            foregroundBrandPrimary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundBrandReverse: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            foregroundDanger: CheddarColor(red: 0.54902, green: 0.03922, blue: 0.12941, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.80784, green: 0.7451, blue: 1, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            bgOnBrand: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            bgDanger: CheddarColor(red: 1, green: 0.89412, blue: 0.91373, opacity: 1),
            bgScrim: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            iconSecondary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.95176, green: 0.94, blue: 0.97365, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.92765, green: 0.91, blue: 0.96047, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            borderDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            borderStrong: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            borderFocus: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            borderDanger: CheddarColor(red: 0.84706, green: 0.10588, blue: 0.23529, opacity: 1),
            trackDefault: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            shadowSurface: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 0.08),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.2)
            )
        }
    case .dark:
        switch brand {
        case .magenta:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundOnSurfaceTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            bgBrandPrimary: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            iconSecondary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.13177, green: 0.0502, blue: 0.08863, opacity: 1),
            backgroundSurface: CheddarColor(red: 0.19451, green: 0.07906, blue: 0.13412, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.22682, green: 0.09333, blue: 0.1578, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.52),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        case .blue:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundOnSurfaceTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            bgBrandPrimary: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            bgBrandShade: CheddarColor(red: 0, green: 0.48235, blue: 0.93333, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            iconSecondary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.06118, green: 0.0502, blue: 0.16549, opacity: 1),
            backgroundSurface: CheddarColor(red: 0.09569, green: 0.07906, blue: 0.24173, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.11388, green: 0.09333, blue: 0.28078, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.52),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        case .green:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundOnSurfaceTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            bgBrandPrimary: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.35294, green: 0.72941, blue: 0, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            iconSecondary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.06118, green: 0.09726, blue: 0.05334, opacity: 1),
            backgroundSurface: CheddarColor(red: 0.09569, green: 0.14494, blue: 0.08471, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.11388, green: 0.16862, blue: 0.10133, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.52),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        case .purple:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundOnSurfaceTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            bgBrandPrimary: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.46667, green: 0.27843, blue: 1, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            iconSecondary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.09255, green: 0.0502, blue: 0.16549, opacity: 1),
            backgroundSurface: CheddarColor(red: 0.13961, green: 0.07906, blue: 0.24173, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.16408, green: 0.09333, blue: 0.28078, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.52),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.32),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        }
    case .brand:
        switch brand {
        case .magenta:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 1, green: 0.92157, blue: 0.99216, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.78824, green: 0.06275, blue: 0.60784, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            iconSecondary: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.52157, green: 0, blue: 0.33725, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 0.72),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 1, green: 0.56863, blue: 0.94902, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0.39216, green: 0, blue: 0.17647, opacity: 0.45),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        case .blue:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.83922, green: 0.97255, blue: 1, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            bgBrandShade: CheddarColor(red: 0, green: 0.48235, blue: 0.93333, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            iconSecondary: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0, green: 0.18824, blue: 0.8, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 0.72),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 0.33725, green: 0.84314, blue: 1, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0.03922, green: 0, blue: 0.56078, opacity: 0.45),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        case .green:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.94902, green: 1, blue: 0.81961, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.35294, green: 0.72941, blue: 0, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            iconSecondary: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.05882, green: 0.36471, blue: 0, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 0.72),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0.03922, green: 0.23529, blue: 0, opacity: 0.45),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        case .purple:
            return Semantic(
            foregroundPrimary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            foregroundSecondary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.6),
            foregroundTertiary: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.1),
            foregroundBrandPrimary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundBrandSecondary: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            foregroundBrandTertiary: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            foregroundBrandHighlight: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundOnReverse: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            foregroundOnReverseSecondary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            foregroundBrandReverse: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            foregroundBrandReverseSecondary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            foregroundBrandReverseTertiary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            foregroundDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            foregroundSuccess: CheddarColor(red: 0.6902, green: 0.99608, blue: 0, opacity: 1),
            foregroundWarning: CheddarColor(red: 1, green: 0.5451, blue: 0, opacity: 1),
            foregroundOnSurface: CheddarColor(red: 0, green: 0, blue: 0, opacity: 1),
            foregroundOnSurfaceSecondary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.56),
            foregroundOnSurfaceTertiary: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.08),
            bgBrandPrimary: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            bgBrandSecondary: CheddarColor(red: 0.91765, green: 0.89804, blue: 1, opacity: 1),
            bgBrandTertiary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            bgBrandShade: CheddarColor(red: 0.46667, green: 0.27843, blue: 1, opacity: 1),
            bgOnBrand: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            bgDanger: CheddarColor(red: 0.2902, green: 0.01569, blue: 0.06275, opacity: 1),
            bgScrim: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            iconPrimary: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            iconSecondary: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            backgroundDefault: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 1),
            backgroundSurface: CheddarColor(red: 1, green: 1, blue: 1, opacity: 1),
            backgroundMuted: CheddarColor(red: 0.31373, green: 0.03529, blue: 0.82745, opacity: 1),
            backgroundOverlay: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 0.72),
            borderDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            borderStrong: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.4),
            borderFocus: CheddarColor(red: 0.66667, green: 0.5451, blue: 1, opacity: 1),
            borderDanger: CheddarColor(red: 1, green: 0.42745, blue: 0.52157, opacity: 1),
            trackDefault: CheddarColor(red: 1, green: 1, blue: 1, opacity: 0.2),
            shadowSurface: CheddarColor(red: 0.19608, green: 0, blue: 0.56078, opacity: 0.45),
            shadowControl: CheddarColor(red: 0, green: 0, blue: 0, opacity: 0.4)
            )
        }
        }
    }
}
