#!/usr/bin/env node
/**
 * Generates TypeScript token bindings from packages/cheddar-tokens/cheddar.tokens.json
 *
 * Swift bindings are not generated here — the design system publishes its own
 * `dist/platforms/swift/CheddarTokens.swift`, which `npm run sync:swift` vendors into
 * apps/ios. That export is authoritative because it also carries typography, and the
 * dark/brand appearances that live in the tokens' `$extensions`.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const tokensPath = path.join(root, 'packages/cheddar-tokens/cheddar.tokens.json')
const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'))

/** @type {Map<string, { hex?: string, alpha?: number, ref?: string }>} */
const colorMap = new Map()

function walkColors(obj, prefix = 'color') {
  if (!obj || typeof obj !== 'object') return
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue
    const pathKey = `${prefix}.${key}`
    if (value.$value !== undefined) {
      if (typeof value.$value === 'string' && value.$value.startsWith('{')) {
        colorMap.set(pathKey, { ref: value.$value.slice(1, -1) })
      } else if (value.$value?.hex) {
        colorMap.set(pathKey, {
          hex: value.$value.hex,
          alpha: value.$value.alpha,
        })
      }
    } else if (typeof value === 'object') {
      walkColors(value, pathKey)
    }
  }
}

walkColors(tokens.color, 'color')

function resolve(entry) {
  if (entry.hex) return entry
  if (entry.ref) return resolve(colorMap.get(entry.ref) ?? {})
  return { hex: '#000000' }
}

const primitivePaths = [...colorMap.keys()].filter(
  (k) => !k.includes('semantic') && !colorMap.get(k).ref,
)

let ts = `/** Generated by scripts/generate-tokens.mjs — do not edit. */\n\nexport const tokenColor = {\n`
for (const pathKey of primitivePaths.sort()) {
  const resolved = resolve(colorMap.get(pathKey))
  const key = pathKey.replace('color.', '').replace(/\./g, '_')
  ts += `  ${JSON.stringify(key)}: ${JSON.stringify(resolved.hex)},\n`
}
ts += `} as const\n\nexport const tokenSize = {\n`

for (const [group, value] of Object.entries(tokens.size)) {
  if (group.startsWith('$') || value.$value) continue
  for (const [key, leaf] of Object.entries(value)) {
    if (key.startsWith('$') || !leaf.$value?.unit) continue
    ts += `  ${JSON.stringify(`${group}.${key}`)}: ${leaf.$value.value},\n`
  }
}
ts += `} as const\n`

const tsOut = path.join(root, 'packages/cheddar-tokens/generated/tokens.ts')
fs.mkdirSync(path.dirname(tsOut), { recursive: true })
fs.writeFileSync(tsOut, ts)
console.log('Wrote', path.relative(root, tsOut))
